#!/usr/bin/env bash
# Writes the 9 Chiang Mai buy/rent/sold property fixtures directly into the
# staging Properties table (staging-sale-sync-properties), bypassing the API
# entirely — one `aws dynamodb transact-write-items` call per property, using
# request files pre-generated by generate-dynamodb-seed-requests.py.
#
# WARNING: this writes straight to DynamoDB with no auth, no Zod validation,
# and no assertRealEstateOrg gate — those all live in the Lambda, which this
# script skips. Review scripts/dynamodb-seed/*.transact.json before running;
# each is a plain, inspectable aws cli --cli-input-json payload (PK/SK/GSI
# keys computed to exactly match PropertyService.createProperty's own key
# builders in api/properties/services/property.service.ts).
#
# Requires: an AWS CLI profile/credentials with write access to
# staging-sale-sync-properties in ap-southeast-2.
#
# Usage:
#   ./scripts/import-wello-chiang-mai-properties-dynamodb.sh [aws-profile]
#
# Regenerate the request files first if you've edited the payload JSON:
#   python3 scripts/generate-dynamodb-seed-requests.py

set -euo pipefail

REGION="ap-southeast-2"
PROFILE_ARGS=()
if [[ -n "${1:-}" ]]; then
    PROFILE_ARGS=(--profile "$1")
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEED_DIR="$SCRIPT_DIR/dynamodb-seed"

shopt -s nullglob
REQUEST_FILES=("$SEED_DIR"/*.transact.json)
shopt -u nullglob

if [[ ${#REQUEST_FILES[@]} -eq 0 ]]; then
    echo "No *.transact.json files found in $SEED_DIR — run generate-dynamodb-seed-requests.py first." >&2
    exit 1
fi

for f in "${REQUEST_FILES[@]}"; do
    echo "==> $(basename "$f")"
    aws dynamodb transact-write-items \
        --region "$REGION" \
        "${PROFILE_ARGS[@]}" \
        --cli-input-json "file://$f"
    echo "    ok"
done

echo
echo "Done. Verify with, e.g.:"
echo "  aws dynamodb query --region $REGION ${PROFILE_ARGS[*]} --table-name staging-sale-sync-properties \\"
echo "    --key-condition-expression 'PK = :pk AND begins_with(SK, :prefix)' \\"
echo "    --expression-attribute-values '{\":pk\":{\"S\":\"ORG#563453ec-9dac-45f3-969e-e2a4ae4fff62#PROPERTY\"},\":prefix\":{\"S\":\"PROPERTY#\"}}' \\"
echo "    --query 'Items[].data.S' --output text"
